[profile.default]
src = 'contracts'
out = 'out'
test = 'test2'
libs = ['lib']
optimizer = true
optimizer_runs = 200
gas_reports = ["TaikoL1", "TaikoWithConfig", "TaikoL2",  "GasComparision", "SignalService", "Bridge", "BridgedERC20", "TaikoToken", "EtherVault", "TokenVault"]
allow_paths = ["../../node_modules"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
remappings = [
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
  '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
]
